### PR TITLE
docs: add roadmap.md

### LINKED ISSUE #2: Add a roadmap for python
Add a proper documentation for python roadmap

### PR DESCRIPTION
**Pull request by galahad42**
closes #2

### CODE REVIEW

**Comment by galahad42** [comment]
Please review my PR @kumar-kalyan

**Review by kumar-kalyan — COMMENTED** [review]
Good

**Review by kumar-kalyan — COMMENTED** [review]
looks good

**Review by hackbeatsorg — APPROVED** [review]
nice

**Comment by hackbeatsorg** [comment]
nice

**Review by kumar-kalyan — APPROVED** [review]

**Pull request closed without merging**
