### PR TITLE
update

### PR DESCRIPTION
**Pull request by Adi-Abhishek**

### CODE REVIEW

**Comment by hackbeatsorg** [comment]
nice but follow our syllabus Edit your diagram then open PR

**Comment by Adi-Abhishek** [comment]
can I add image or not or should I just make changes to the readme file like combining them in topics and their subtopics

**Review by kumar-kalyan — CHANGES_REQUESTED** [review]
please add the roadmap under the syllabus

**Comment by Adi-Abhishek** [comment]
#27 IS it right or not

**Pull request merged**
